const schools = [
  "Select School",
  "Business",
  "English, Communication and Philosophy",
  "Geography and Planning",
  "History, Archaeology and Religion",
  "Journalism, Media and Culture",
  "Law and Politics",
  "Modern Languages",
  "Music",
  "Social Sciences",
  "Welsh",
  "School of BioSciences",
  "Dentistry",
  "Healthcare Sciences",
  "Medicine",
  "Optometry and Vision Sciences",
  "Pharmacy and Pharmaceutical Sciences",
  "Psychology",
  "Architecture",
  "Chemistry",
  "Computer Science and Informatics",
  "Earth and Ocean Sciences",
  "Engineering",
  "Mathematics",
  "Physics and Astronomy",
];

export default schools;
