const schoolColleges = {
    "Business": "Arts, Humanities and Social Sciences",
    "English, Communication and Philosophy": "Arts, Humanities and Social Sciences",
    "Geography and Planning": "Arts, Humanities and Social Sciences",
    "History, Archaeology and Religion": "Arts, Humanities and Social Sciences",
    "Journalism, Media and Culture": "Arts, Humanities and Social Sciences",
    "Law and Politics": "Arts, Humanities and Social Sciences",
    "Modern Languages": "Arts, Humanities and Social Sciences",
    "Music": "Arts, Humanities and Social Sciences",
    "Social Sciences": "Arts, Humanities and Social Sciences",
    "Welsh": "Arts, Humanities and Social Sciences",
    "Biosciences": "Biomedical and Life Sciences",
    "Dentistry": "Biomedical and Life Sciences",
    "Healthcare Sciences": "Biomedical and Life Sciences",
    "Medicine": "Biomedical and Life Sciences",
    "Optometry and Vision Sciences": "Biomedical and Life Sciences",
    "Pharmacy and Pharmaceutical Sciences": "Biomedical and Life Sciences",
    "Psychology": "Biomedical and Life Sciences",
    "Architecture": "Physical Sciences and Engineering",
    "Chemistry": "Physical Sciences and Engineering",
    "Computer Science and Informatics": "Physical Sciences and Engineering",
    "Earth and Ocean Sciences": "Physical Sciences and Engineering",
    "Engineering": "Physical Sciences and Engineering",
    "Mathematics": "Physical Sciences and Engineering",
    "Physics and Astronomy": "Physical Sciences and Engineering",
};

export default schoolColleges;
